version: '3.8'
services:
  backend:
    build:
      context: ./backend
    image: chatapp-backend
    container_name: chatapp-backend
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - chatapp-net

  frontend:
    build:
      context: ./frontend
    image: chatapp-frontend
    container_name: chatapp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chatapp-net
networks:
  chatapp-net:
    driver: bridge